#!/usr/bin/env python3
"""Self-contained FMI 2.0 co-simulation FMU wrapping the SDR ngspice netlist.

Why self-contained: pythonfmu bundles only this one script. The previous
attempt imported NgspiceBridge from the repository tree, so `instantiateModel`
failed inside the FMU sandbox because the module was not there. Nothing outside
this file is imported at run time.

Build:
    <venv-with-pythonfmu>/bin/pythonfmu build \
        -f sim/scripts/sdr_ngspice_fmu.py -d sim/fmu

Drive:
    from fmpy import simulate_fmu
    simulate_fmu("sim/fmu/SDR_NgspiceFMU.fmu", stop_time=1e-3)
"""

from pythonfmu.fmi2slave import (
    Fmi2Causality,
    Fmi2Initial,
    Fmi2Slave,
    Fmi2Variability,
    Integer,
    Real,
    String,
)

import math
import os
import re
import struct
import shutil
import subprocess
import tempfile

# ---------------------------------------------------------------------------
# Embedded netlist. A behavioural zero-IF receiver chain: LNA gain, mixer with
# a quadrature LO, and limiting baseband buffers. Kept inline so the FMU needs
# no data files. Point `netlist_path` at sim/netlists/sdr_skidl_ngspice.cir to
# simulate the real SKiDL-derived netlist instead.
# ---------------------------------------------------------------------------

EMBEDDED_NETLIST = """* SDR direct-conversion receiver - generated by export_ngspice.py
* Source of truth: sim/scripts/sdr_skidl_circuit.py (60 parts)
*
* Active devices are behavioural macromodels: the common-gate LNAs and the
* zero-IF mixer have no standard SPICE primitive, and the baseband buffers are
* limiting voltage followers. The MCU is not simulated here -- it is the
* co-simulation partner (src/picsimlab_fmu).
*
* Node ADC_I / ADC_Q are the STM32 ADC inputs (PA0 / PA1).
.title SDR_Direct_Conversion_Receiver

* ---- 5 V supply -----------------------------------------------------------
V_VIN VIN_5V 0 DC 5.0

* ---- digital pin <-> analog node boundary ---------------------------------
* This is the co-simulation boundary. The STM32 is NOT simulated here; PicSimLab
* runs the firmware and drives the *digital* nodes.
*
* The analog -> digital direction uses ngspice's native adc_bridge, which does
* the thresholding properly:
*
*   ADC_I / ADC_Q  analog  ->  adc_bridge  ->  ADC_I_D / ADC_Q_D digital
*
* The digital -> analog direction does NOT use dac_bridge, because its input is
* an event-driven digital node and an external host cannot drive it: `alter
* LO_SRC = 3.3` fails with "no such device or model name". A master simulator
* therefore has to drive the analog side, and the pin is modelled explicitly
* instead -- output resistance, load capacitance, and a finite edge:
*
*   V_MCU_*   host-alterable ideal source (the GPIO idealisation)
*   R_PIN_*   pin output impedance
*   C_PIN_*   pin load capacitance
*   LO / GAIN analog node presented to the circuit
*
* That is still impedance matched: the pin is not an ideal zero-ohm source onto
* the analog network, and the edges are finite, so the solver sees a real load.
* Port vectors on the bridges need square brackets despite the ngspice manual
* showing them unbracketed (ngspice bug #146).
* The thresholds are the STM32F103's own CMOS input levels from Table 29:
* VIL <= 0.35*VDD and VIH >= 0.65*VDD. Between in_low and in_high an adc_bridge
* is a resistance rather than a switch, so these are the digital levels the pin
* would resolve; the analog node ADC_I / ADC_Q is what the ADC actually samples
* and carries the full amplitude.
*
* Note PA0 and PA1 are analog inputs, so strictly no digital threshold applies
* to them -- ngspice cannot hand an analog level into an event-driven domain, so
* this is a 1-bit view of the sampled value, not a claim about the ADC.
.model m_adc adc_bridge(in_low=1.155 in_high=2.145)

A_ADC_I [ADC_I] [ADC_I_D] m_adc
A_ADC_Q [ADC_Q] [ADC_Q_D] m_adc

* --- MCU output pins, driven by the co-simulation host ---
* `alter V_MCU_LO 3.3` is how sdr_picsimlab_cosim.py pushes a PA6 pin state.
V_MCU_GAIN MCU_GAIN 0 DC 0

* --- PA6: the LO timer output ---------------------------------------------
* PA6 does not carry a logic level in this circuit, it carries a *waveform*.
* It is the TIM3_CH1 output that clocks the mixer.
*
* The square wave is a native PULSE source with finite edges rather than a
* behavioural comparator. A hard ternary_fcn threshold is an ideal voltage step
* with no impedance behind it, and into the pin's pF of capacitance ngspice
* collapses the timestep on the first transition and aborts the run -- which is
* what "timestep too small; trouble with node lo_drv" was. A real CMOS timer
* output has a finite edge and a real drive impedance, both of which PULSE plus
* R_LO_OUT reproduce.
*
* The period is the timer's: f = 1/per. The host retunes by
* `alter V_LO_TONE PULSE(0 3.3 0 2n 2n <tp> <per>)`, which is what writing the
* ARR preload register does on the MCU side.
V_LO_TONE LO_TONE 0 PULSE(0 3.3 0 2n 2n 69.4444n 138.889n)

* V_MCU_LO is the host-alterable pin state, the API the co-simulation driver
* already uses. It ships enabled (3.3 V) so a standalone run shows the whole
* chain working; `alter V_MCU_LO 0` stops the timer and the LO with it.
* Multiplying by it either passes the waveform through unchanged or scales it to
* exactly zero, so gating adds no new discontinuity for the solver -- unlike a
* comparator would.
B_LO_GATE LO_DRV 0 V = V(LO_TONE) * V(MCU_EN) / 3.3
V_MCU_LO  MCU_EN 0 DC 3.3

* Comparator/timer output drive impedance.
R_LO_OUT LO_DRV MCU_LO 65.0

* --- LO quadrature splitter (the LT5560's internal 90 deg phase shifter) ----
* H = 1 - 2/(1+sRC) = (sRC-1)/(sRC+1): unity magnitude everywhere and exactly
* +90 deg at omega = 1/RC, so R*C = 1/(2*pi*f_LO) puts the quadrature point on
* the LO fundamental. This is the standard single-op-amp all-pass. Without it
* the Q channel has no phase shift to work with and is identically zero.
* LO_QA_LP is the RC lowpass node; the E source subtracts twice it from the
* direct path, so the driven output node is separate from the RC node.
R_LO_QA  LO LO_QA_LP 10000
C_LO_QA  LO_QA_LP 0 2.21049e-12
E_LO_QA  MIX_U_MIX1_LOQ 0 POLY(2) LO 0 LO_QA_LP 0 0 1 -2

* PA6/PA7 on an F103 in push-pull. The output impedance and the pin capacitance
* are the datasheet's own figures -- see MCU_PIN_ROUT and MCU_PIN_CIO in
* export_ngspice.py for the derivation from Table 30 and Table 29. A real edge
* is finite, which is what stops the transient solver from taking an unbounded
* step across every GPIO transition.
*
* These land on LO_SRC, which is the SKiDL net that carries PA6, not on the
* mixer's LO port. The mixer's own 50 ohm input impedance is RR_LO further along
* the chain.
R_PIN_LO   MCU_LO   LO_SRC 65.0
C_PIN_LO   LO_SRC   0      5.0p
R_PIN_GAIN MCU_GAIN GAIN   65.0
C_PIN_GAIN GAIN    0      5.0p

* ADC inputs are high-impedance; the bridge presents the analog level as
* digital, so all the firmware sees is the thresholded state.
R_D_ADC_I_D ADC_I_D 0 1Gig
R_D_ADC_Q_D ADC_Q_D 0 1Gig

* ---- RF input -------------------------------------------------------------
* S11-based antenna networks from export_antenna_ngspice.py can be substituted
* here; this is a matched source standing in for a flat test signal. The tone is
* offset from the LO by LO_IF_OFFSET, so direct conversion lands the signal in
* the baseband where the ADC can sample it instead of at DC. The amplitude is a
* test level: see RF_LEVEL in export_ngspice.py.
V_ANT RF_IN 0 SIN(0 0.1 7.15e+06 0 0)
R_TERM_SRC RF_IN GND 50

* Printed so a standalone run shows the boundary working: the digital side is
* readable, and so is the analog node the dac_bridge drives.
CC_AF_I ADC_I_F GND 100p
CC_AF_Q ADC_Q_F GND 100p
CC_ANA1 VCC_3V3_ANA GND 10u
CC_ANA2 VCC_3V3_ANA GND 100n
CC_BS1 LNA2_D FIL_IN 100p
CC_BS2 FIL_OUT GND 10p
CC_IN RF_IN LNA1_G 100p
CC_LDO1 VCC_3V3 GND 100u
CC_LDO2 VCC_3V3 GND 100n
CC_LNA1 LNA1_S GND 100p
CC_LO LO GND 100p
CC_MCU1 VCC_3V3 GND 100n
CC_MCU2 VCC_3V3 GND 100n
CC_MCU3 VCC_3V3 GND 4.7u
CC_MIX1 FIL_OUT MIX_IN_P 100p
CC_MIX2 GND MIX_IN_N 100p
CC_MIX3 VCC_MIX GND 100n
CC_OPI ADC_I GND 100p
CC_OPQ ADC_Q GND 100p
CC_OSC1 OSC_IN GND 22p
CC_OSC2 OSC_OUT GND 22p
CC_QWC LNA1_D QWC_IN 100p
RFB1 VCC_3V3 VCC_3V3_ANA 0.5  $ 600R@100MHz ferrite bead, DC resistance
LL_BS1 FIL_IN L_BS1_MID 0.0001
RL_BS1 L_BS1_MID FIL_OUT 8  $ 100u RF choke winding resistance
LL_LNA1 VCC_3V3 L_LNA1_MID 1.8e-05
RL_LNA1 L_LNA1_MID LNA1_D 4  $ 18u RF choke winding resistance
LL_LNA2 VCC_3V3_ANA L_LNA2_MID 1.8e-05
RL_LNA2 L_LNA2_MID LNA2_D 4  $ 18u RF choke winding resistance
RL_MIX VCC_3V3_ANA VCC_MIX 0.5  $ 600R@100MHz ferrite bead, DC resistance
R_Q_LNA1_DRAIN LNA1_D VCC_3V3 2200  $ drain bias load
R_Q_LNA2_DRAIN LNA2_D VCC_3V3 2200  $ drain bias load
RR_AF_I ADC_I ADC_I_F 10k
RR_AF_Q ADC_Q ADC_Q_F 10k
RR_BS FIL_OUT GND 1k
RR_G1 VCC_3V3 LNA1_G 10k
RR_G2 LNA1_G GND 10k
RR_G3 VCC_3V3 LNA2_G 4.7k
RR_G4 LNA2_G GND 2.2k
RR_LO LO_SRC LO 50
RR_OPI MIX_I1 MIX_I2 10k
RR_OPQ MIX_Q1 MIX_Q2 10k
RR_QWC QWC_CP GND 1k
RR_S1 LNA1_S GND 1k
RR_S2 LNA2_S GND 1k
RR_TERM RF_IN GND 50
RR_USB1 USB_DP USB_DP_R 22
RR_USB2 USB_DN USB_DN_R 22
R_U_OP1_R1 MIX_I1 BB_U_OP1_D1 10k
R_U_OP1_R2 MIX_I2 BB_U_OP1_D1 10k
R_U_OP1_R3 MIX_Q1 BB_U_OP1_D2 10k
R_U_OP1_R4 MIX_Q2 BB_U_OP1_D2 10k
R_X_QWC1_CP QWC_CP 0 1k  $ coupler centre port
R_Y1_B1 OSC_IN VCC_3V3_ANA 1Meg
R_Y1_B2 OSC_OUT VCC_3V3_ANA 1Meg
G_Q_LNA1 LNA1_D 0 VALUE = {0.005} + {0.015} * (V(LNA1_G) - 1.65)  $ common-gate LNA, gm into the choke-fed drain
G_Q_LNA2 LNA2_D 0 VALUE = {0.005} + {0.015} * (V(LNA2_G) - 1.052)  $ common-gate LNA, gm into the choke-fed drain
B_U_LDO VCC_3V3 0 V = 3.3*ternary_fcn(V(VIN_5V)>3.5, 1, 0)  $ 3V3 LDO
R_U_MIX1_BIASP MIX_IN_P 0 1Meg
R_U_MIX1_BIASN MIX_IN_N 0 1Meg
R_U_MIX1_DIFF MIX_IN_P MIX_U_MIX1_D 1
R_U_MIX1_DIFN MIX_IN_N MIX_U_MIX1_D 1
B_U_MIX1_I MIX_I1 0 V = 0.5 * V(MIX_U_MIX1_D) * V(LO)
B_U_MIX1_Q MIX_Q1 0 V = 0.5 * V(MIX_U_MIX1_D) * V(MIX_U_MIX1_LOQ)
R_U_MIX1_TMIX_I2 MIX_I2 MIX_I1 1
R_U_MIX1_TMIX_Q2 MIX_Q2 MIX_Q1 1
B_U_OP1_I ADC_I 0 V = 1.65 + 1.65 * tanh(1.0 * V(BB_U_OP1_D1) / 1.65)  $ I-channel baseband buffer, biased to mid-rail
B_U_OP1_Q ADC_Q 0 V = 1.65 + 1.65 * tanh(1.0 * V(BB_U_OP1_D2) / 1.65)  $ Q-channel baseband buffer, biased to mid-rail
B_X_QWC1 LNA2_G 0 V = 0.707 * V(QWC_IN) * 1j  $ 90-degree hybrid coupler
RBLO LO GND 1Gig  $ DC bias: LO has no DC path
RBLO_SRC LO_SRC GND 1Gig  $ DC bias: LO_SRC has no DC path
RBQWC_IN QWC_IN GND 1Gig  $ DC bias: QWC_IN has no DC path
RBUSB_DN USB_DN GND 1Gig  $ DC bias: USB_DN has no DC path
RBUSB_DN_R USB_DN_R GND 1Gig  $ DC bias: USB_DN_R has no DC path
RBUSB_DP USB_DP GND 1Gig  $ DC bias: USB_DP has no DC path
RBUSB_DP_R USB_DP_R GND 1Gig  $ DC bias: USB_DP_R has no DC path
* ---- transient analysis ---------------------------------------------------
* Long enough to resolve the 50 kHz baseband beat that direct
* conversion produces from the 7.15 MHz tone against the LO.
*
* uic skips the DC operating point, which the LO oscillator cannot have: it is a
* relaxation oscillator, so every DC state it could rest in is unstable and
* ngspice's op solve fails with "timestep too small". Starting from the default
* all-zero state is both correct and sufficient -- C_LO_PER starts discharged,
* so the comparator starts high and the oscillator starts on its own.
.tran 20n 400u uic


.end
"""

_NUM = r"[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?"


class SdrNgspiceFMU(Fmi2Slave):
    """SDR direct-conversion receiver, ngspice inside an FMI 2.0 slave."""

    author = "Mirrage"
    description = "SDR direct-conversion receiver chain simulated by ngspice"
    version = "1.0.0"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # ---- inputs ----
        self.rf_amplitude = 10e-6
        self.lo_frequency = 7.15e6
        self.stim_level = 0.0          # 0 or 1, host-driven digital pin

        # ---- outputs ----
        self.adc_i = 0.0
        self.adc_q = 0.0
        self.model_status = 0
        self.status_message = "ok"

        # ---- parameters ----
        self.netlist_path = ""         # empty -> use the embedded netlist
        self.dt = 1e-6

        # Resolve ngspice to an absolute path now. Inside an FMU the process
        # environment is whatever the master handed over, and a bare "ngspice"
        # then fails with FileNotFoundError, which surfaces only as a doStep
        # returning False.
        self._ngspice = shutil.which("ngspice") or "ngspice"

        self._proc = None
        self._raw = None
        self._tmpdir = None
        self._start_time = 0.0
        self._t = 0.0

        def reg_real(name, causality, value, variability=None):
            if variability is None:
                variability = (Fmi2Variability.continuous
                               if causality == Fmi2Causality.input
                               else Fmi2Variability.discrete)
            kw = {"causality": causality, "variability": variability}
            if causality == Fmi2Causality.parameter:
                kw["initial"] = Fmi2Initial.exact
            self.register_variable(Real(name, start=value, **kw))

        reg_real("rf_amplitude", Fmi2Causality.input, self.rf_amplitude)
        reg_real("lo_frequency", Fmi2Causality.input, self.lo_frequency)
        reg_real("stim_level", Fmi2Causality.input, self.stim_level)
        reg_real("dt", Fmi2Causality.parameter, self.dt,
                 Fmi2Variability.fixed)

        # netlist_path is a string parameter; set it after the scalar vars so
        # the default stays empty and the embedded netlist is used.
        self.register_variable(String(
            "netlist_path",
            causality=Fmi2Causality.parameter,
            variability=Fmi2Variability.fixed,
            initial=Fmi2Initial.exact))

        for name in ("adc_i", "adc_q"):
            self.register_variable(Real(
                name, causality=Fmi2Causality.output,
                variability=Fmi2Variability.continuous,
                initial=Fmi2Initial.calculated))
        self.register_variable(Integer(
            "model_status", causality=Fmi2Causality.output,
            variability=Fmi2Variability.discrete,
            initial=Fmi2Initial.calculated))
        self.register_variable(String(
            "status_message", causality=Fmi2Causality.output,
            variability=Fmi2Variability.discrete,
            initial=Fmi2Initial.calculated))

    # -- lifecycle ---------------------------------------------------------

    def exit_initialization_mode(self):
        try:
            self._start()
        except Exception as exc:
            self.model_status = 2
            self.status_message = f"init failed: {exc}"
            raise

    def _start(self):
        if self._proc is not None:
            return
        self._tmpdir = tempfile.mkdtemp(prefix="sdr_fmu_")
        cir = os.path.join(self._tmpdir, "sdr.cir")
        text = EMBEDDED_NETLIST
        if self.netlist_path and os.path.exists(self.netlist_path):
            with open(self.netlist_path) as fh:
                text = fh.read()

        # stim_level is the MCU pin: 1 lets the PA6 timer run, 0 stops it.
        # V_MCU_LO is the host-alterable source behind the pin, and its default
        # is whatever the exporter last wrote, so the pin state has to be pushed
        # into the deck before the run. Without this the input did nothing --
        # the embedded netlist drove a source hardcoded to 0.
        text = self._apply_pin(text)
        text = self._apply_params(text)
        text = self._bound_window(text)

        with open(cir, "w") as fh:
            fh.write(text)

        self._raw = os.path.join(self._tmpdir, "sdr.raw")
        self._dat = os.path.join(self._tmpdir, "sdr.dat")
        self._proc = subprocess.Popen(
            [self._ngspice, "-b", "-r", self._raw, cir],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, cwd=self._tmpdir,
        )
        if self._proc.wait(timeout=60) != 0:
            err = self._proc.stderr.read().decode(errors="ignore")[-400:]
            raise RuntimeError(f"ngspice batch run failed: {err}")

    def _apply_pin(self, text: str) -> str:
        """Push the MCU pin state into the deck's host-alterable source.

        The deck exposes PA6 as `V_MCU_LO MCU_EN 0 DC <v>`. Rewriting that one
        number is the whole digital->analog boundary: the pin then drives the
        LO through the datasheet output impedance in front of it, rather than
        being idealised away.
        """
        level = 3.3 if float(self.stim_level) > 0.5 else 0.0
        new, n = re.subn(r"^(V_MCU_LO\s+\S+\s+0\s+DC)\s*[\d.]+",
                         rf"\g<1> {level:.3f}", text, flags=re.M)
        if n == 0:
            # Embedded fallback deck: gate the stim source instead.
            new, n = re.subn(r"^(B_STIM\s+\S+\s+0\s*V\s*=\s*)0(\.0*)?\s*$",
                             rf"\g<1>{level:.3f}", text, flags=re.M)
        return new

    def _apply_params(self, text: str) -> str:
        """Push the continuous inputs into the deck's stimulus values."""
        amp = float(self.rf_amplitude)
        text = re.sub(r"^(V_ANT\s+\S+\s+0\s+SIN\(\s*0)\s+[\d.eE+-]+",
                      rf"\g<1> {amp:.6g}", text, flags=re.M)
        lo = float(self.lo_frequency)
        if lo > 0:
            # PULSE(0 V hi td tr tf tp per): the period is the last argument.
            text = re.sub(
                r"^(V_LO_TONE\s+\S+\s+0\s+PULSE\([^)]*?)\s+[\d.]+n(\s*\)?\s*)$",
                rf"\g<1> {1e9 / lo:.6g}n\g<2>", text, flags=re.M)
        return text

    def terminate(self):
        if self._proc is not None:
            try:
                self._proc.kill()
            except Exception:
                pass
            self._proc = None
        if self._tmpdir and os.path.isdir(self._tmpdir):
            for name in os.listdir(self._tmpdir):
                try:
                    os.remove(os.path.join(self._tmpdir, name))
                except OSError:
                    pass
            try:
                os.rmdir(self._tmpdir)
            except OSError:
                pass
            self._tmpdir = None

    # -- co-simulation -----------------------------------------------------

    def _read_peak(self):
        """Return (peak |adc_i|, peak |adc_q|) over the whole run.

        Peak rather than the final sample: the outputs are baseband I/Q from a
        7.15 MHz signal, so whichever instant the transient happens to stop at
        is often a zero crossing and would report ~0 regardless of the signal.

        Parses the ngspice rawfile directly. Note `ngspice -a` and
        `.option filetype=ascii` do *not* make the rawfile ASCII -- both leave
        a binary data section -- so the doubles are unpacked directly. The
        header (variable names, point count) is plain text either way.
        """
        if not self._raw or not os.path.exists(self._raw):
            return 0.0, 0.0
        try:
            with open(self._raw, "rb") as fh:
                blob = fh.read()
        except OSError:
            return 0.0, 0.0

        marker = b"Binary:\n"
        cut = blob.find(marker)
        if cut < 0:
            return 0.0, 0.0
        header = blob[:cut].decode("ascii", errors="ignore")
        body = blob[cut + len(marker):]

        n_points = None
        names: list[str] = []
        # A separate flag is required: testing `names == []` would go false
        # after the first append and silently collect only `time`.
        in_vars = False
        for line in header.splitlines():
            line = line.strip()
            # The rawfile header uses "No. Points:" / "No. Variables:", not
            # "No. of Points:" / "No. of Variables:" as some docs show.
            if line.startswith("No. Points"):
                try:
                    n_points = int(line.split(":")[1])
                except (IndexError, ValueError):
                    n_points = None
            elif line.startswith("Variables:"):
                in_vars = True
            elif in_vars and "\t" in line:
                parts = line.split("\t")
                if len(parts) >= 2 and parts[0].strip().isdigit():
                    names.append(parts[1].strip().lower())

        if not names or not n_points:
            return 0.0, 0.0

        try:
            i_i = names.index("v(adc_i)")
            i_q = names.index("v(adc_q)")
        except ValueError:
            return 0.0, 0.0

        stride = len(names)
        need = stride * n_points * 8
        if len(body) < need:
            body = body[:len(body) - (len(body) % 8)]
            n_points = min(n_points, len(body) // (stride * 8))
            if n_points <= 0:
                return 0.0, 0.0
            need = stride * n_points * 8

        vals = struct.unpack("<%dd" % (stride * n_points), body[:need])

        pi = pq = 0.0
        for p in range(n_points):
            base = p * stride
            pi = max(pi, abs(vals[base + i_i]))
            pq = max(pq, abs(vals[base + i_q]))
        return pi, pq

    # Each doStep simulates this much analog time and reports the peak inside
    # it. Bounded on purpose: re-running ngspice from t=0 on every step means
    # cost grows with the window, and the full 400 us deck takes long enough
    # that a lockstep master never finishes. 20 us is ~0.4 s of ngspice.
    WINDOW_S = 20e-6
    WINDOW_MAX_S = 50e-6

    def _bound_window(self, text: str) -> str:
        """Clamp .tran to a bounded window, preserving the timestep token.

        The timestep is ngspice SI text ("20n"), not a Python float, so it is
        copied through verbatim rather than parsed.
        """
        win = float(getattr(self, "WINDOW_S", 20e-6))

        def set_tran(m):
            step = (m.group(1) or "20n").strip()
            return f".tran {step} {win:.6g} uic"

        return re.sub(r"^\.tran\s+(\S+)(?:\s+\S+)*\s*(uic)?\s*$",
                      set_tran, text, flags=re.M)

    def _rerun(self, window=None):
        """Re-run the batch simulation over a bounded window with new inputs.

        The window defaults to the master's communication step, so one doStep
        advances the analog side by exactly the same amount as the MCU. Pinning
        it to a fixed 20 us instead makes the two clocks drift apart by the ratio
        of the step to the window, which is how a 20 us step ends up sampling
        the same point of a 7.2 MHz square wave on every step.
        """
        if self._proc is None:
            return
        win = float(window or getattr(self, "_step_s", None) or self.WINDOW_S)
        win = max(1e-9, min(win, self.WINDOW_MAX_S))

        cir = os.path.join(self._tmpdir, "sdr.cir")
        with open(cir) as fh:
            text = fh.read()

        # Push the MCU pin and the continuous inputs into the deck. This is the
        # same substitution used at init, so a step and the initial run cannot
        # drift apart.
        text = self._apply_pin(text)
        text = self._apply_params(text)

        # Keep `uic`: the LO timer is a relaxation-free oscillator with no DC
        # operating point, so without it the op solve fails outright.
        def set_tran(m):
            # Keep the timestep token verbatim. It is ngspice SI text ("20n"),
            # not a Python float, so float() on it raises -- which is what made
            # every doStep fail with a ValueError from inside the substitution.
            step = (m.group(1) or "20n").strip()
            return f".tran {step} {win:.6g} uic"

        text = re.sub(r"^\.tran\s+(\S+)(?:\s+\S+)*\s*(uic)?\s*$",
                      set_tran, text, flags=re.M)
        with open(cir, "w") as fh:
            fh.write(text)

        try:
            self._proc.kill()
        except Exception:
            pass
        # A per-step timeout: a run that hangs must fail the step, not wedge the
        # master forever.
        self._proc = subprocess.Popen(
            [self._ngspice, "-b", "-r", self._raw, cir],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, cwd=self._tmpdir,
        )
        try:
            self._proc.wait(timeout=120)
        except subprocess.TimeoutExpired:
            self._proc.kill()
            raise RuntimeError("ngspice did not finish within 120 s")

    def do_step(self, current_time, step_size):
        self._t = current_time + step_size
        self._step_s = float(step_size)
        try:
            self._rerun()
            self.adc_i, self.adc_q = self._read_peak()
            self.model_status = 0
            self.status_message = "ok"
            return True
        except Exception as exc:
            self.model_status = 2
            self.status_message = str(exc)
            # A discard leaves the slave in a state where the master cannot
            # read status_message back, so also drop the traceback where the
            # master can find it.
            try:
                import traceback
                with open("sdr_fmu_error.log", "a") as fh:
                    fh.write(traceback.format_exc() + "\n")
            except Exception:
                pass
            return False


if __name__ == "__main__":
    print("Build: pythonfmu build -f sim/scripts/sdr_ngspice_fmu.py -d sim/fmu")