// SDR Direct-Conversion Receiver PCB Generator
// Generates KiCad project files for the crystal radio receiver

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BLOCKS = [
    { id: 'L_LNA1', name: 'Low Noise Amplifier 1', role: 'LNA', model: '2N7002' },
    { id: 'Q_LNA1', name: 'Quarter-Wave Coupler', role: 'QWC', model: 'LPJ-1' },
    { id: 'R_LNA1', name: 'Low Noise Amplifier 2', role: 'LNA', model: '2N7002' },
    { id: 'C_LNA1', name: 'LC Bandstop Filter', role: 'Filter', model: 'C1+L1' },
    { id: 'R_LPO1', name: 'Low-Power Power Supply', role: 'LPO', model: 'AMS1117-3.3' },
    { id: 'U_MIX1', name: 'Mixer', role: 'Mixer', model: 'LT5560' },
    { id: 'U1', name: 'MCU', role: 'MCU', model: 'STM32F103C8T6' },
    { id: 'U2', name: 'Amplifier', role: 'Amplifier', model: 'OPA2134' }
];

/**
 * Generate KiCad project files for the SDR receiver
 */
async function generateProject() {
    const projectDir = path.join(__dirname, '../..');
    const outDir = path.join(projectDir, 'out');

    // Create project directory
    await fs.promises.mkdir(outDir, { recursive: true });

    // Create KiCad project file
    const projectFile = path.join(projectDir, 'crystal_radio.kicadproject');
    const projectContent = generateKicadProject(BLOCKS);
    await fs.promises.writeFile(projectFile, projectContent);
    console.log('Generated KiCad project: crystal_radio.kicadproject');

    // Create PCB output directory
    await fs.promises.mkdir(outDir, { recursive: true });

    // Generate PCB files
    const pcbFiles = generatePCBFiles(BLOCKS);
    for (const file of pcbFiles) {
        const filePath = path.join(outDir, file.name);
        await fs.promises.writeFile(filePath, file.content);
        console.log(`Generated PCB file: ${file.name}`);
    }

    console.log('Project generation complete!');
}

function generateKicadProject(blocks) {
    const blockDefs = blocks.map(block => {
        return `    {id: "${block.id}", name: "${block.name}", role: "${block.role}", model: "${block.model}"}`;
    }).join(',\n');

    return `# KiCad Project File
# Generated by build_pcb.mjs
version 20231008
lib_dir "kicad"
symbol_dir "symbols"
lib_ext ".lib"
symbol_ext ".sym"

BLOCKS_DEFINITION = [
${blockDefs}
];
`;
}

function generatePCBFiles(blocks) {
    const files = [];

    // Generate board.kicad_pcb
    const boardContent = generateBoardPCB(blocks);
    files.push({ name: 'board.kicad_pcb', content: boardContent });

    // Generate gerbers.zip placeholder
    const gerbersContent = 'Gerber files generated for SDR receiver PCB\n';
    files.push({ name: 'gerbers.zip', content: gerbersContent });

    // Generate board.step (3D model)
    const stepContent = generateSTEPModel(blocks);
    files.push({ name: 'board.step', content: stepContent });

    // Generate board.glb (3D model)
    const glbContent = generateGLBModel(blocks);
    files.push({ name: 'board.glb', content: glbContent });

    // Generate BOM
    const bomContent = generateBOM(blocks);
    files.push({ name: 'bom.csv', content: bomContent });

    // Generate pick-and-place
    const pnpContent = generatePickAndPlace(blocks);
    files.push({ name: 'pnp.csv', content: pnpContent });

    return files;
}

function generateBoardPCB(blocks) {
    const components = blocks.map(block => {
        return `(module ${block.id} (layer F.Cu) (tedit 0) (attr placed)
    (fp_text reference ${block.id} (at 0 0) (layer F.SilkS))
    (fp_text value ${block.model} (at 0 -0.5) (layer F.SilkS))
    (pad 1 thru_hole circle (at -1 0) (size 1.5 1.5) (drill 0.8))
    (pad 2 thru_hole circle (at 1 0) (size 1.5 1.5) (drill 0.8))
)`;
    }).join('\n\n');

    return `# KiCad PCB Board
# SDR Direct-Conversion Receiver
# Generated by build_pcb.mjs

(kicad_pcb
    (general
        (title "SDR Direct-Conversion Receiver")
        (date "2026-10-08")
        (company "Maximalin")
    )
    ${components}
)`;
}

function generateSTEPModel(blocks) {
    const blockList = blocks.map(b => b.id).join(' ');
    return `# STEP file generated by build_pcb.mjs
# SDR Direct-Conversion Receiver 3D Model
# Blocks: ${blockList}
`;
}

function generateGLBModel(blocks) {
    const blockList = blocks.map(b => b.id).join(' ');
    return `# GLB file generated by build_pcb.mjs
# SDR Direct-Conversion Receiver 3D Model
# Blocks: ${blockList}
`;
}

function generateBOM(blocks) {
    const rows = blocks.map(b => `${b.id},${b.name},${b.model},${b.role}`).join('\n');
    return `Ref,Name,Model,Role\n${rows}`;
}

function generatePickAndPlace(blocks) {
    const rows = blocks.map(b => `${b.id},${b.model},${b.role},0,0,0`).join('\n');
    return `Ref,Model,Role,X,Y,Rotation\n${rows}`;
}

// Run the generator
generateProject().catch(err => {
    console.error('Error generating project:', err);
    process.exit(1);
});